# Generated by Django 6.1 on 2026-09-01 23:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sunkist_grower_no', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'ordering': ['sunkist_grower_no'],
            },
        ),
        migrations.CreateModel(
            name='ModelSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cci_dg_max', models.FloatField(default=-7.0, help_text='Mean CCI below this is dark green.')),
                ('cci_lg_max', models.FloatField(default=-3.0, help_text='Mean CCI at or below this (and above DG) is light green.')),
                ('cci_s_max', models.FloatField(default=2.0, help_text='Mean CCI at or below this (and above LG) is silver. Above is yellow.')),
                ('prior_drift_dg', models.FloatField(default=0.1, help_text='CCI per day for lots received dark green (55 F).')),
                ('prior_drift_lg', models.FloatField(default=0.15)),
                ('prior_drift_s', models.FloatField(default=0.25)),
                ('prior_drift_y', models.FloatField(default=0.25)),
                ('start_cci_dg', models.FloatField(default=-10.0, help_text='Assumed CCI at receipt for an unsampled dark green lot.')),
                ('start_cci_lg', models.FloatField(default=-5.0)),
                ('start_cci_s', models.FloatField(default=-0.5)),
                ('start_cci_y', models.FloatField(default=4.0)),
                ('buffer_days', models.PositiveIntegerField(default=7, help_text='pack_by = predicted yellow date minus this.')),
                ('decay_flag_pct', models.FloatField(default=2.0, help_text='Decay rate (percent) at or above which the lot is flagged.')),
                ('min_fruit_for_score', models.PositiveIntegerField(default=6, help_text='Photos with fewer detected fruit are marked failed.')),
                ('max_horizon_days', models.PositiveIntegerField(default=365, help_text='Cap on how far ahead a yellow date is projected when drift is tiny.')),
                ('sample_overdue_days', models.PositiveIntegerField(default=10)),
                ('import_gap_days', models.PositiveIntegerField(default=120)),
            ],
            options={
                'verbose_name': 'model settings',
                'verbose_name_plural': 'model settings',
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(help_text='Famous plant code, e.g. SLA1.', max_length=10, unique=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('report_recipients', models.TextField(blank=True, help_text="Comma-separated email addresses that receive this plant's Monday report.")),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('receiving', 'Receiving'), ('packout', 'Packout'), ('room_moves', 'Room moves')], max_length=12)),
                ('file', models.FileField(blank=True, upload_to='imports/%Y/%m/')),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('rows_ok', models.PositiveIntegerField(default=0)),
                ('rows_failed', models.PositiveIntegerField(default=0)),
                ('error_report', models.JSONField(blank=True, default=list)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'import batches',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_no', models.CharField(help_text='Famous lot id, unique within a plant.', max_length=30)),
                ('block', models.CharField(blank=True, max_length=50)),
                ('variety', models.CharField(choices=[('Eureka', 'Eureka'), ('Lisbon', 'Lisbon'), ('Other', 'Other')], default='Lisbon', max_length=10)),
                ('receive_date', models.DateField()),
                ('receiving_color', models.CharField(choices=[('DG', 'Dark green'), ('LG', 'Light green'), ('S', 'Silver'), ('Y', 'Yellow')], default='DG', max_length=2)),
                ('bins_received', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_storage', 'In storage'), ('packed', 'Packed'), ('dumped', 'Dumped')], default='in_storage', max_length=12)),
                ('packed_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('grower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='lots.grower')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='lots.plant')),
            ],
            options={
                'ordering': ['plant__code', 'receive_date', 'lot_no'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('room_type', models.CharField(choices=[('storage', 'Storage'), ('degreening', 'Degreening')], default='storage', max_length=12)),
                ('target_temp_f', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='lots.plant')),
            ],
            options={
                'ordering': ['plant__code', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LotRoomMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moved_at', models.DateField()),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_moves', to='lots.lot')),
                ('moved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moves_in', to='lots.room')),
            ],
            options={
                'ordering': ['-moved_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='lot',
            name='current_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lots', to='lots.room'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='lots.plant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Packout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packed_date', models.DateField()),
                ('cartons_fancy', models.PositiveIntegerField(default=0)),
                ('cartons_choice', models.PositiveIntegerField(default=0)),
                ('cartons_standard', models.PositiveIntegerField(default=0)),
                ('cartons_products', models.PositiveIntegerField(default=0)),
                ('cartons_total', models.PositiveIntegerField(default=0, editable=False)),
                ('fresh_pct', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=5, null=True)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packouts', to='lots.lot')),
                ('source_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packouts', to='lots.importbatch')),
            ],
            options={
                'ordering': ['-packed_date'],
                'constraints': [models.UniqueConstraint(fields=('lot', 'packed_date'), name='one_packout_per_lot_day')],
            },
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('plant', 'name'), name='unique_room_per_plant'),
        ),
        migrations.AddIndex(
            model_name='lot',
            index=models.Index(fields=['plant', 'status'], name='lots_lot_plant_i_ad6f8f_idx'),
        ),
        migrations.AddConstraint(
            model_name='lot',
            constraint=models.UniqueConstraint(fields=('plant', 'lot_no'), name='unique_lot_per_plant'),
        ),
    ]
