# Generated by Django 6.1 on 2026-09-02 13:47

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0003_import_plant_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='harvest_date',
            field=models.DateField(blank=True, help_text='Harvest date when known. This separates preharvest maturity from storage time.', null=True),
        ),
        migrations.AddField(
            model_name='lot',
            name='intake_cci_mean',
            field=models.FloatField(blank=True, help_text='Measured mean CCI at receipt; preferred over the categorical receiving color.', null=True),
        ),
        migrations.AddField(
            model_name='lot',
            name='intake_cci_std',
            field=models.FloatField(blank=True, help_text='Within-lot CCI standard deviation at receipt.', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='packout',
            name='chilling_injury_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Observed chilling injury percent at packout.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AddField(
            model_name='packout',
            name='meets_spec',
            field=models.BooleanField(blank=True, help_text='Whether the run met the intended customer or house quality specification.', null=True),
        ),
        migrations.AddField(
            model_name='packout',
            name='shrivel_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Observed shriveled fruit percent at packout.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AddField(
            model_name='packout',
            name='soft_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Observed soft fruit percent at packout.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='kind',
            field=models.CharField(choices=[('receiving', 'Receiving'), ('packout', 'Packout'), ('room_moves', 'Room moves'), ('conditions', 'Room conditions'), ('treatments', 'Lot treatments')], max_length=12),
        ),
        migrations.CreateModel(
            name='LotTreatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField()),
                ('treatment_type', models.CharField(choices=[('ethylene', 'Ethylene degreening'), ('wax', 'Wax or coating'), ('fungicide', 'Fungicide'), ('1_mcp', '1-MCP'), ('ga3', 'Gibberellic acid (GA3)'), ('2_4_d', '2,4-D'), ('other', 'Other')], max_length=12)),
                ('product', models.CharField(blank=True, max_length=100)),
                ('concentration', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('concentration_unit', models.CharField(blank=True, help_text='For example ppm, percent, oz/gal, or label rate.', max_length=20)),
                ('duration_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('notes', models.CharField(blank=True, max_length=250)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='lots.lot')),
                ('source_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lot_treatments', to='lots.importbatch')),
            ],
            options={
                'ordering': ['lot', 'applied_at'],
                'indexes': [models.Index(fields=['lot', 'applied_at'], name='lots_lottre_lot_id_515bff_idx')],
                'constraints': [models.UniqueConstraint(fields=('lot', 'applied_at', 'treatment_type', 'product'), name='unique_lot_treatment_event')],
            },
        ),
        migrations.CreateModel(
            name='RoomCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField()),
                ('temperature_f', models.DecimalField(decimal_places=2, max_digits=6)),
                ('relative_humidity_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('ethylene_ppm', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('co2_pct', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('source', models.CharField(default='csv', max_length=80)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='lots.room')),
                ('source_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_conditions', to='lots.importbatch')),
            ],
            options={
                'ordering': ['room', 'recorded_at'],
                'indexes': [models.Index(fields=['room', 'recorded_at'], name='lots_roomco_room_id_b01605_idx')],
                'constraints': [models.UniqueConstraint(fields=('room', 'recorded_at', 'source'), name='unique_room_condition_reading')],
            },
        ),
    ]
