# Generated by Django 6.1 on 2026-09-06 14:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0004_lot_harvest_date_lot_intake_cci_mean_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lotroommove',
            name='unique_room_move_per_lot_day',
        ),
        migrations.AddField(
            model_name='lotroommove',
            name='occurred_at',
            field=models.DateTimeField(blank=True, help_text='Actual move timestamp when known. Blank means only the date is known.', null=True),
        ),
        migrations.AddConstraint(
            model_name='lotroommove',
            constraint=models.UniqueConstraint(fields=('lot', 'room', 'occurred_at'), name='unique_room_move_timestamp'),
        ),
        migrations.AddConstraint(
            model_name='lotroommove',
            constraint=models.UniqueConstraint(condition=models.Q(('occurred_at__isnull', True)), fields=('lot', 'room', 'moved_at'), name='unique_date_only_room_move'),
        ),
    ]
