# Generated by Django 6.1 on 2026-09-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0005_remove_lotroommove_unique_room_move_per_lot_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelsettings',
            name='color_correction_method',
            field=models.CharField(choices=[('linear', 'Linear 3x3 matrix on all nine patches'), ('curve', 'Per-channel grey-ramp curve, then linear matrix')], default='linear', help_text='Photo color correction. The curve option first matches each channel through the six grey patches (tone/gamma), then fits the matrix. Photos already scored keep their method until rescored.', max_length=8),
        ),
        migrations.AddField(
            model_name='modelsettings',
            name='sample_fruit_count',
            field=models.PositiveIntegerField(default=25, help_text='Fruit inspected for defects in a routine sample. USDA lemon inspection uses 25; ten of them are photographed on the board. When decay meets the flag percent the foreman is asked to inspect a second set and record the combined count.'),
        ),
        migrations.AddField(
            model_name='modelsettings',
            name='temperature_response',
            field=models.BooleanField(default=True, help_text='Scale prior degreening rates by the room setpoint using the bell-shaped temperature response (fastest near 15 °C, slow at 5 °C, halted near 25 °C). Fitted slopes are never scaled.'),
        ),
        migrations.AddField(
            model_name='modelsettings',
            name='warm_storage_temp_c',
            field=models.FloatField(default=13.0, help_text='Room setpoint (°C) at or above which storage days count toward the rot-risk clock. Lemons hold 4-6 months near 10 °C but 1-2 months at 13 °C.'),
        ),
        migrations.AddField(
            model_name='modelsettings',
            name='warm_weeks_flag',
            field=models.PositiveIntegerField(default=8, help_text='Weeks at or above the warm threshold at which the rot-risk clock is flagged on the board.'),
        ),
    ]
