# Generated by Django 6.1 on 2026-09-13 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0007_report_recipients_table_and_moved_on'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lotroommove',
            options={'ordering': ['-moved_on', '-id']},
        ),
        migrations.RemoveConstraint(
            model_name='lotroommove',
            name='unique_date_only_room_move',
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lotroommove',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='room_moves', to='lots.lot'),
        ),
        migrations.AlterField(
            model_name='lotroommove',
            name='moved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lottreatment',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treatments', to='lots.lot'),
        ),
        migrations.AlterField(
            model_name='packout',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packouts', to='lots.lot'),
        ),
        migrations.AddConstraint(
            model_name='lot',
            constraint=models.CheckConstraint(condition=models.Q(('harvest_date__isnull', True), ('harvest_date__lte', models.F('receive_date')), _connector='OR'), name='harvest_not_after_receipt'),
        ),
        migrations.AddConstraint(
            model_name='lotroommove',
            constraint=models.UniqueConstraint(condition=models.Q(('occurred_at__isnull', True)), fields=('lot', 'room', 'moved_on'), name='unique_date_only_room_move'),
        ),
    ]
