# Generated by Django 6.1 on 2026-09-13 21:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0009_packout_generated_columns'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LotChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source', models.CharField(blank=True, help_text='web:<path>, import:<kind>, packout, command:<name>.', max_length=120)),
                ('field', models.CharField(max_length=40)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lot_changes', to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='lots.lot')),
            ],
            options={
                'ordering': ['-changed_at', '-id'],
                'indexes': [models.Index(fields=['lot', 'changed_at'], name='lots_lotcha_lot_id_aa01e5_idx')],
            },
        ),
    ]
