# Generated by Django 6.1 on 2026-09-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0010_lotchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelsettings',
            name='hold_days_dg',
            field=models.PositiveIntegerField(default=165, help_text='Hold budget in days for a dark green lot: how long it can stay marketable at that stage. Trade guidance: 5 to 6 months.'),
        ),
        migrations.AddField(
            model_name='modelsettings',
            name='hold_days_lg',
            field=models.PositiveIntegerField(default=60, help_text='Hold budget for a light green lot; about 2 months.'),
        ),
        migrations.AddField(
            model_name='modelsettings',
            name='hold_days_s',
            field=models.PositiveIntegerField(default=42, help_text='Hold budget for a silver lot; about 6 weeks.'),
        ),
        migrations.AddField(
            model_name='modelsettings',
            name='hold_days_y',
            field=models.PositiveIntegerField(default=14, help_text='Hold budget once a lot has turned yellow; weeks, not months.'),
        ),
        migrations.AddField(
            model_name='modelsettings',
            name='hold_decay_days_per_pct',
            field=models.FloatField(default=3.0, help_text='Hold budget days removed per percent decay observed in the recent samples.'),
        ),
        migrations.AddField(
            model_name='modelsettings',
            name='hold_warm_multiplier',
            field=models.FloatField(default=2.0, help_text='Each day in a room at or above the warm threshold spends this many days of hold budget. Lemons hold 4 to 6 months near 10 C but 1 to 2 months at 13 C.'),
        ),
    ]
