# Generated by Django 6.1 on 2026-09-13 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DimDate',
            fields=[
                ('date_key', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField(unique=True)),
                ('year', models.SmallIntegerField()),
                ('quarter', models.SmallIntegerField()),
                ('month', models.SmallIntegerField()),
                ('week_of_year', models.SmallIntegerField()),
                ('day_of_week', models.SmallIntegerField(help_text='ISO: Monday is 1.')),
                ('is_monday', models.BooleanField()),
            ],
            options={
                'db_table': 'dw_dim_date',
                'ordering': ['date_key'],
            },
        ),
        migrations.CreateModel(
            name='DimPlant',
            fields=[
                ('plant_key', models.BigIntegerField(help_text='lots_plant.id', primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('weekly_pack_capacity_bins', models.DecimalField(decimal_places=1, max_digits=9, null=True)),
            ],
            options={
                'db_table': 'dw_dim_plant',
            },
        ),
        migrations.CreateModel(
            name='DimLot',
            fields=[
                ('lot_key', models.BigIntegerField(help_text='lots_lot.id', primary_key=True, serialize=False)),
                ('lot_no', models.CharField(max_length=30)),
                ('grower_no', models.CharField(max_length=20)),
                ('grower_name', models.CharField(max_length=100)),
                ('block', models.CharField(blank=True, max_length=50)),
                ('variety', models.CharField(max_length=10)),
                ('receiving_color', models.CharField(max_length=2)),
                ('intake_cci_mean', models.FloatField(null=True)),
                ('bins_received', models.IntegerField(null=True)),
                ('status', models.CharField(max_length=12)),
                ('days_in_storage', models.IntegerField()),
                ('harvest_date', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='warehouse.dimdate')),
                ('packed_date', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='warehouse.dimdate')),
                ('receive_date', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='warehouse.dimdate')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='warehouse.dimplant')),
            ],
            options={
                'db_table': 'dw_dim_lot',
            },
        ),
        migrations.CreateModel(
            name='FactDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_version', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('action', models.CharField(max_length=16)),
                ('status', models.CharField(max_length=10)),
                ('reason', models.CharField(blank=True, max_length=20)),
                ('market_regime', models.CharField(blank=True, max_length=12)),
                ('after_lock', models.BooleanField()),
                ('decided_by', models.CharField(blank=True, max_length=150)),
                ('source_decision_id', models.BigIntegerField(help_text='forecast_plandecision.id', unique=True)),
                ('decided_date', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='warehouse.dimdate')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='warehouse.dimlot')),
                ('plan_date', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='warehouse.dimdate')),
                ('planned_pack_date', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='warehouse.dimdate')),
                ('recommended_pack_by_date', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='warehouse.dimdate')),
            ],
            options={
                'db_table': 'dw_fact_decision',
            },
        ),
        migrations.CreateModel(
            name='FactPackout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartons_fancy', models.IntegerField()),
                ('cartons_choice', models.IntegerField()),
                ('cartons_standard', models.IntegerField()),
                ('cartons_products', models.IntegerField()),
                ('cartons_total', models.IntegerField()),
                ('fresh_pct', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('bins_packed', models.DecimalField(decimal_places=1, max_digits=9, null=True)),
                ('is_final', models.BooleanField()),
                ('packout_color', models.CharField(blank=True, max_length=2)),
                ('decay_pct', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('meets_spec', models.BooleanField(null=True)),
                ('days_in_storage', models.IntegerField()),
                ('days_after_pack_by', models.IntegerField(help_text='Positive means packed late against the forecast.', null=True)),
                ('forecast_pack_by_date', models.ForeignKey(help_text='Pack-by date of the latest forecast made on or before the pack date.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='warehouse.dimdate')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packouts', to='warehouse.dimlot')),
                ('packed_date', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='warehouse.dimdate')),
            ],
            options={
                'db_table': 'dw_fact_packout',
                'constraints': [models.UniqueConstraint(fields=('lot', 'packed_date'), name='dw_one_packout_per_lot_day')],
            },
        ),
        migrations.CreateModel(
            name='FactPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_to_pack_by', models.IntegerField(null=True)),
                ('cci_now', models.FloatField()),
                ('stage', models.CharField(max_length=2)),
                ('drift_per_day', models.FloatField()),
                ('decay_rate', models.FloatField()),
                ('decay_flag', models.BooleanField()),
                ('confidence', models.CharField(max_length=4)),
                ('n_points', models.SmallIntegerField()),
                ('method', models.CharField(blank=True, max_length=40)),
                ('model_version', models.CharField(max_length=40)),
                ('as_of_date', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='warehouse.dimdate')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='warehouse.dimlot')),
                ('pack_by_date', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='warehouse.dimdate')),
            ],
            options={
                'db_table': 'dw_fact_prediction',
                'constraints': [models.UniqueConstraint(fields=('lot', 'as_of_date'), name='dw_one_prediction_per_lot_day')],
            },
        ),
    ]
