# Generated by Django 6.1 on 2026-09-14 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factprediction',
            name='deadline_kind',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='factprediction',
            name='hold_days_remaining',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='factprediction',
            name='hold_until_date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='warehouse.dimdate'),
        ),
    ]
