# Generated by Django 6.1 on 2026-09-01 23:22

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import sampling.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lots', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sampled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('foreman_color', models.CharField(choices=[('DG', 'Dark green'), ('LG', 'Light green'), ('S', 'Silver'), ('Y', 'Yellow')], max_length=2)),
                ('foreman_pack_within_weeks', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('decay_count', models.PositiveSmallIntegerField(default=0)),
                ('fruit_count', models.PositiveSmallIntegerField(default=10)),
                ('notes', models.TextField(blank=True)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='lots.lot')),
                ('sampled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sampled_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SamplePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=sampling.models.photo_upload_path)),
                ('thumb', models.FileField(blank=True, help_text='Small JPEG made by the scoring job for the board.', upload_to='thumbs/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('card_detected', models.BooleanField(default=False)),
                ('fruit_detected', models.PositiveSmallIntegerField(default=0)),
                ('per_fruit_lab', models.JSONField(blank=True, default=list)),
                ('per_fruit_cci', models.JSONField(blank=True, default=list)),
                ('mean_cci', models.FloatField(blank=True, null=True)),
                ('std_cci', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scored', 'Scored'), ('failed', 'Failed')], default='pending', max_length=8)),
                ('error', models.TextField(blank=True)),
                ('pipeline_version', models.CharField(blank=True, max_length=40)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='sampling.sample')),
            ],
            options={
                'ordering': ['-uploaded_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='sample',
            index=models.Index(fields=['lot', 'sampled_at'], name='sampling_sa_lot_id_e182cc_idx'),
        ),
        migrations.AddIndex(
            model_name='samplephoto',
            index=models.Index(fields=['status', 'uploaded_at'], name='sampling_sa_status_3ff986_idx'),
        ),
    ]
