# Generated by Django 6.1 on 2026-09-02 13:47

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0004_lot_harvest_date_lot_intake_cci_mean_and_more'),
        ('sampling', '0002_audit_and_scoring_quality'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='chilling_injury_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sample',
            name='failure_reason',
            field=models.CharField(blank=True, choices=[('color', 'Color'), ('decay', 'Decay'), ('shrivel', 'Shrivel'), ('soft', 'Softness'), ('chilling', 'Chilling injury'), ('rind', 'Rind breakdown'), ('other', 'Other')], max_length=10),
        ),
        migrations.AddField(
            model_name='sample',
            name='firmness_score',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 — soft'), (2, '2 — yielding'), (3, '3 — fairly firm'), (4, '4 — firm'), (5, '5 — very firm')], null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='marketability',
            field=models.CharField(blank=True, choices=[('pass', 'Meets pack specification'), ('fail', 'Failed pack specification')], help_text='Required for shelf-life holdout assessments.', max_length=4),
        ),
        migrations.AddField(
            model_name='sample',
            name='purpose',
            field=models.CharField(choices=[('routine', 'Routine monitoring'), ('holdout', 'Shelf-life holdout')], default='routine', max_length=8),
        ),
        migrations.AddField(
            model_name='sample',
            name='rind_breakdown_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sample',
            name='sampled_bins_count',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AddField(
            model_name='sample',
            name='selection_method',
            field=models.CharField(choices=[('across_bins', 'Random fruit across bins'), ('fixed_holdout', 'Fixed holdout group'), ('convenience', 'Convenience sample'), ('unknown', 'Not recorded')], default='unknown', max_length=16),
        ),
        migrations.AddField(
            model_name='sample',
            name='shrivel_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sample',
            name='soft_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='sample',
            constraint=models.CheckConstraint(condition=models.Q(('soft_count__lte', models.F('fruit_count'))), name='sample_soft_not_above_fruit_count'),
        ),
        migrations.AddConstraint(
            model_name='sample',
            constraint=models.CheckConstraint(condition=models.Q(('shrivel_count__lte', models.F('fruit_count'))), name='sample_shrivel_not_above_fruit_count'),
        ),
        migrations.AddConstraint(
            model_name='sample',
            constraint=models.CheckConstraint(condition=models.Q(('chilling_injury_count__lte', models.F('fruit_count'))), name='sample_chilling_not_above_fruit_count'),
        ),
        migrations.AddConstraint(
            model_name='sample',
            constraint=models.CheckConstraint(condition=models.Q(('rind_breakdown_count__lte', models.F('fruit_count'))), name='sample_rind_not_above_fruit_count'),
        ),
    ]
