# Generated by Django 6.1 on 2026-09-06 14:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0005_remove_lotroommove_unique_room_move_per_lot_day_and_more'),
        ('sampling', '0003_sample_chilling_injury_count_sample_failure_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplephoto',
            name='calibration_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='Station and measured references copied at capture; retained when rescoring.'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='foreman_pack_within_weeks',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(8)]),
        ),
        migrations.CreateModel(
            name='BoardCalibration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_id', models.CharField(max_length=80)),
                ('phone_id', models.CharField(max_length=80)),
                ('light_id', models.CharField(max_length=80)),
                ('measured_at', models.DateTimeField()),
                ('instrument', models.CharField(help_text='Instrument, illuminant and measurement record identifier.', max_length=200)),
                ('reference_rgb', models.JSONField(help_text='All nine patch names mapped to measured D65 sRGB values [R,G,B], each 0–255. Never enter nominal print targets as measurements.')),
                ('active', models.BooleanField(default=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lots.plant')),
            ],
            options={
                'ordering': ['-measured_at', '-pk'],
            },
        ),
    ]
