# Generated by Django 6.1 on 2026-09-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampling', '0004_samplephoto_calibration_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardcalibration',
            name='device_model',
            field=models.CharField(blank=True, help_text='Phone make and model, e.g. iPhone 15 or Pixel 8a. Camera response differs by device.', max_length=80),
        ),
        migrations.AddField(
            model_name='boardcalibration',
            name='white_balance_mode',
            field=models.CharField(blank=True, help_text='White-balance setting locked on the phone camera, e.g. Daylight or 5000K. Auto white balance shifts color between shots and must not be used.', max_length=40),
        ),
        migrations.AddField(
            model_name='sample',
            name='capture_seconds',
            field=models.PositiveIntegerField(blank=True, help_text='Seconds from opening the capture screen to saving. The pilot target is a 90-second median.', null=True),
        ),
        migrations.AddField(
            model_name='samplephoto',
            name='device_info',
            field=models.CharField(blank=True, help_text='Browser user agent at upload, so photos can be grouped by phone when reviewing calibration.', max_length=200),
        ),
    ]
