# Generated by Django 6.1 on 2026-09-13 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0008_delete_rules_and_constraints'),
        ('sampling', '0005_capture_time_device_and_wb'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='samples', to='lots.lot'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sampled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sample',
            name='voided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voided_lemon_samples', to=settings.AUTH_USER_MODEL),
        ),
    ]
