# Generated by Django 6.1 on 2026-09-13 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampling', '0006_delete_rules_and_constraints'),
    ]

    operations = [
        migrations.CreateModel(
            name='FruitMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField(help_text='Position in the photo, 0-based, as detected by the pipeline.')),
                ('lab_l', models.FloatField(blank=True, null=True)),
                ('lab_a', models.FloatField(blank=True, null=True)),
                ('lab_b', models.FloatField(blank=True, null=True)),
                ('cci', models.FloatField(blank=True, help_text='Null when b* is too close to zero for a usable index.', null=True)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fruit', to='sampling.samplephoto')),
            ],
            options={
                'ordering': ['photo', 'index'],
                'constraints': [models.UniqueConstraint(fields=('photo', 'index'), name='one_measurement_per_fruit')],
            },
        ),
    ]
