# Generated by Django 6.1 on 2026-09-01 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_of_date', models.DateField()),
                ('cci_now', models.FloatField()),
                ('stage', models.CharField(choices=[('DG', 'Dark green'), ('LG', 'Light green'), ('S', 'Silver'), ('Y', 'Yellow')], max_length=2)),
                ('drift_per_day', models.FloatField()),
                ('predicted_yellow_date', models.DateField(blank=True, null=True)),
                ('pack_by_date', models.DateField(blank=True, null=True)),
                ('decay_rate', models.FloatField(default=0.0, help_text='Fraction, 0-1, over the last two samples.')),
                ('decay_flag', models.BooleanField(default=False)),
                ('confidence', models.CharField(choices=[('low', 'Low'), ('med', 'Medium'), ('high', 'High')], default='low', max_length=4)),
                ('model_version', models.CharField(max_length=40)),
                ('inputs', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='lots.lot')),
            ],
            options={
                'ordering': ['-as_of_date', '-id'],
                'indexes': [models.Index(fields=['lot', 'as_of_date'], name='forecast_pr_lot_id_1e2ac1_idx')],
                'constraints': [models.UniqueConstraint(fields=('lot', 'as_of_date'), name='one_prediction_per_lot_day')],
            },
        ),
    ]
