# Generated by Django 6.1 on 2026-09-05 20:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0002_report_delivery'),
        ('lots', '0004_lot_harvest_date_lot_intake_cci_mean_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PackPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_date', models.DateField()),
                ('version', models.PositiveIntegerField(help_text='Increments per plant with every publish.')),
                ('source', models.CharField(choices=[('report', 'Monday report'), ('board', 'Published from the board'), ('command', 'Management command')], default='board', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model_version', models.CharField(max_length=40)),
                ('settings_snapshot', models.JSONField(blank=True, default=dict)),
                ('locked_at', models.DateTimeField(blank=True, help_text='When the GM locked the week schedule against this plan.', null=True)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_plans', to=settings.AUTH_USER_MODEL)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pack_plans', to='lots.plant')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-plan_date', '-version'],
            },
        ),
        migrations.CreateModel(
            name='PlanRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('decay_risk', 'Decay risk'), ('pack_overdue', 'Pack overdue'), ('pack_this_week', 'Pack this week'), ('retake_photo', 'Retake photo'), ('sample_due', 'Sample due'), ('pack_soon', 'Pack soon'), ('scoring', 'Scoring'), ('needs_baseline', 'Needs baseline'), ('monitor', 'Monitor')], max_length=16)),
                ('requires_decision', models.BooleanField(default=False, help_text='True for pack-now and decay actions; management must record a decision.')),
                ('pack_by_date', models.DateField(blank=True, null=True)),
                ('stage', models.CharField(blank=True, choices=[('DG', 'Dark green'), ('LG', 'Light green'), ('S', 'Silver'), ('Y', 'Yellow')], max_length=2)),
                ('cci_now', models.FloatField(blank=True, null=True)),
                ('confidence', models.CharField(blank=True, choices=[('low', 'Low'), ('med', 'Medium'), ('high', 'High')], max_length=4)),
                ('decay_flag', models.BooleanField(default=False)),
                ('bins_remaining', models.DecimalField(blank=True, decimal_places=1, max_digits=9, null=True)),
                ('room_name', models.CharField(blank=True, max_length=50)),
                ('days_in_storage', models.PositiveIntegerField(default=0)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_recommendations', to='lots.lot')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='forecast.packplan')),
                ('prediction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_recommendations', to='forecast.prediction')),
            ],
            options={
                'ordering': ['plan', 'rank'],
            },
        ),
        migrations.CreateModel(
            name='PlanDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('deferred', 'Deferred'), ('overridden', 'Overridden')], max_length=10)),
                ('reason', models.CharField(blank=True, choices=[('customer_order', 'Customer order or ship date'), ('size_grade', 'Size, grade or label demand'), ('capacity', 'Line capacity or labor'), ('changeover', 'Changeover cost or run minimum'), ('quality_disagree', 'Disagree with the model color or quality call'), ('fruit_not_ready', 'Holding for color or maturity'), ('logistics', 'Room access or logistics'), ('data_issue', 'Data issue (quantity, sample or import)'), ('other', 'Other (explain in notes)')], max_length=20)),
                ('planned_pack_date', models.DateField(blank=True, help_text='When management intends to pack instead (required when deferring).', null=True)),
                ('notes', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('after_lock', models.BooleanField(default=False, help_text='Recorded after the plan was locked.')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_decisions', to=settings.AUTH_USER_MODEL)),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='forecast.planrecommendation')),
            ],
            options={
                'ordering': ['-decided_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='packplan',
            index=models.Index(fields=['plant', 'plan_date'], name='forecast_pa_plant_i_ef6090_idx'),
        ),
        migrations.AddConstraint(
            model_name='packplan',
            constraint=models.UniqueConstraint(fields=('plant', 'version'), name='one_plan_version_per_plant'),
        ),
        migrations.AddConstraint(
            model_name='planrecommendation',
            constraint=models.UniqueConstraint(fields=('plan', 'lot'), name='one_recommendation_per_plan_lot'),
        ),
    ]
