# Generated by Django 6.1 on 2026-09-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0003_pack_plan_decisions'),
    ]

    operations = [
        migrations.AddField(
            model_name='planrecommendation',
            name='evidence_notes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='planrecommendation',
            name='action',
            field=models.CharField(choices=[('decay_risk', 'Inspect observed decay'), ('pack_overdue', 'Pack overdue'), ('pack_this_week', 'Pack this week'), ('retake_photo', 'Retake photo'), ('sample_due', 'Sample due'), ('pack_soon', 'Pack soon'), ('scoring', 'Scoring'), ('needs_baseline', 'Needs baseline'), ('monitor', 'Monitor'), ('refresh_forecast', 'Refresh forecast')], max_length=16),
        ),
    ]
