# Generated by Django 6.1 on 2026-09-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0004_planrecommendation_evidence_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packplan',
            name='market_regime',
            field=models.CharField(blank=True, choices=[('tight', 'Tight supply'), ('normal', 'Normal'), ('oversupplied', 'Oversupplied')], help_text='Market context this week as judged by the GM: tight, normal or oversupplied. Copied onto every decision recorded against the plan.', max_length=12),
        ),
        migrations.AddField(
            model_name='plandecision',
            name='market_regime',
            field=models.CharField(blank=True, choices=[('tight', 'Tight supply'), ('normal', 'Normal'), ('oversupplied', 'Oversupplied')], help_text='Market context copied from the plan when the decision was recorded.', max_length=12),
        ),
    ]
