# Generated by Django 6.1 on 2026-09-13 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0005_market_regime'),
        ('lots', '0008_delete_rules_and_constraints'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='packplan',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locked_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='packplan',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pack_plans', to='lots.plant'),
        ),
        migrations.AlterField(
            model_name='packplan',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='published_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='plandecision',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plan_decisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='planrecommendation',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_recommendations', to='lots.lot'),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='predictions', to='lots.lot'),
        ),
        migrations.AlterField(
            model_name='reportdelivery',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_deliveries', to='lots.plant'),
        ),
    ]
