# Generated by Django 6.1 on 2026-09-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0006_delete_rules_and_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='planrecommendation',
            name='deadline_kind',
            field=models.CharField(blank=True, help_text="'hold' or 'pack_by': which date the recommendation acted on.", max_length=8),
        ),
        migrations.AddField(
            model_name='planrecommendation',
            name='hold_until_date',
            field=models.DateField(blank=True, help_text='Hold budget end snapshot.', null=True),
        ),
        migrations.AddField(
            model_name='prediction',
            name='hold_days_remaining',
            field=models.IntegerField(blank=True, help_text='Hold budget left at as_of_date; negative once exhausted.', null=True),
        ),
        migrations.AddField(
            model_name='prediction',
            name='hold_until_date',
            field=models.DateField(blank=True, help_text='as_of_date plus the hold budget remaining.', null=True),
        ),
        migrations.AddField(
            model_name='prediction',
            name='stage_entry_date',
            field=models.DateField(blank=True, help_text='Estimated day the lot entered its current color stage.', null=True),
        ),
        migrations.AlterField(
            model_name='planrecommendation',
            name='pack_by_date',
            field=models.DateField(blank=True, help_text='Color deadline snapshot.', null=True),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='pack_by_date',
            field=models.DateField(blank=True, help_text='Predicted yellow date minus the buffer; the color deadline.', null=True),
        ),
    ]
